/**
 * RC4-2 KPI Formula Registry — single authoritative metric contract catalog.
 * Never recalculate these formulas in React.
 */

import {
  ANALYTICS_TIMEZONE,
  type AnalyticsModuleId,
  type MetricContract,
} from "./types.js";

export const REGISTRY_VERSION = "rc4-2.analytics.v1";

const BASE_PERMS = ["reports.read", "order.manage", "admin.access"] as const;
const FINANCE_PERMS = ["finance.manage", "admin.access", "reports.read"] as const;
const HR_PERMS = ["hr.manage", "staff.manage", "admin.access", "reports.read"] as const;
const INV_PERMS = ["inventory.manage", "admin.access", "reports.read"] as const;
const PUR_PERMS = ["purchasing.manage", "admin.access", "reports.read"] as const;

function c(
  partial: Omit<MetricContract, "timezone" | "organizationScope"> & {
    organizationScope?: boolean;
  },
): MetricContract {
  return {
    timezone: ANALYTICS_TIMEZONE,
    organizationScope: partial.organizationScope ?? true,
    ...partial,
  };
}

export const FORMULA_REGISTRY: MetricContract[] = [
  // —— Sales ——
  c({
    metricId: "sales.gross",
    module: "sales",
    name: "Gross sales",
    formula: "SUM(orders.total_amount) WHERE status NOT IN excluded",
    authoritativeSource: "public.orders",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "No orders in range → 0." },
  }),
  c({
    metricId: "sales.net",
    module: "sales",
    name: "Net sales",
    formula: "gross - discounts - refunds (refunded payments)",
    authoritativeSource: "public.orders + public.payments",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "No orders in range → 0." },
  }),
  c({
    metricId: "sales.aov",
    module: "sales",
    name: "Average order value",
    formula: "gross / order_count (non-cancelled)",
    authoritativeSource: "public.orders",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "null", message: "Null when order_count = 0." },
  }),
  c({
    metricId: "sales.discounts",
    module: "sales",
    name: "Discounts",
    formula: "SUM(orders.discount_amount) WHERE status NOT IN excluded",
    authoritativeSource: "public.orders.discount_amount",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "No discounts → 0." },
  }),
  c({
    metricId: "sales.refunds",
    module: "sales",
    name: "Refunds",
    formula: "SUM(payments.amount) WHERE status = refunded AND order in scope",
    authoritativeSource: "public.payments",
    includedStatuses: ["refunded"],
    excludedStatuses: [],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "No refunded payments → 0." },
  }),
  c({
    metricId: "sales.tax",
    module: "sales",
    name: "Tax collected",
    formula: "SUM(orders.tax_amount) WHERE status NOT IN excluded",
    authoritativeSource: "public.orders.tax_amount",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "No tax rows → 0." },
  }),
  c({
    metricId: "sales.payment_mix",
    module: "sales",
    name: "Payment mix",
    formula: "GROUP BY payments.payment_method SUM(amount) status=paid",
    authoritativeSource: "public.payments",
    includedStatuses: ["paid"],
    excludedStatuses: ["pending", "failed", "refunded"],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "Empty mix when no paid payments." },
  }),
  c({
    metricId: "sales.channel_mix",
    module: "sales",
    name: "Channel mix",
    formula: "GROUP BY orders.order_source COUNT/SUM",
    authoritativeSource: "public.orders.order_source",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "Empty mix when no orders." },
  }),
  c({
    metricId: "sales.series.hourly",
    module: "sales",
    name: "Hourly sales series",
    formula: "Bucket created_at Asia/Karachi hour → SUM(total_amount)",
    authoritativeSource: "public.orders",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "range≤93d",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "Empty hours → 0." },
  }),
  c({
    metricId: "sales.series.daily",
    module: "sales",
    name: "Daily sales series",
    formula: "Bucket created_at Asia/Karachi date → SUM(total_amount)",
    authoritativeSource: "public.orders",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "range≤93d",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "Empty days → 0." },
  }),
  c({
    metricId: "sales.series.weekly",
    module: "sales",
    name: "Weekly sales series",
    formula: "ISO week buckets Asia/Karachi → SUM(total_amount)",
    authoritativeSource: "public.orders",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "range≤93d",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "Empty weeks → 0." },
  }),
  c({
    metricId: "sales.series.monthly",
    module: "sales",
    name: "Monthly sales series",
    formula: "YYYY-MM Asia/Karachi → SUM(total_amount)",
    authoritativeSource: "public.orders",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "range≤93d",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "Empty months → 0." },
  }),
  c({
    metricId: "sales.wow",
    module: "sales",
    name: "Week-over-week change",
    formula: "(gross_current_7d - gross_prior_7d) / gross_prior_7d",
    authoritativeSource: "public.orders",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "rolling-14d ending endDate",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "null", message: "Null when prior week gross = 0." },
  }),
  c({
    metricId: "sales.mom",
    module: "sales",
    name: "Month-over-month change",
    formula: "(gross_current_30d - gross_prior_30d) / gross_prior_30d",
    authoritativeSource: "public.orders",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "rolling-60d ending endDate",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "null", message: "Null when prior month gross = 0." },
  }),
  c({
    metricId: "sales.yoy",
    module: "sales",
    name: "Year-over-year change",
    formula: "(gross_same_range - gross_range_minus_365d) / gross_range_minus_365d",
    authoritativeSource: "public.orders",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "selected range vs −365d",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "null", message: "Null when prior-year gross = 0." },
  }),

  // —— Finance (delegates; no duplicated GL math) ——
  c({
    metricId: "finance.trial_balance",
    module: "finance",
    name: "Trial balance",
    formula: "RPC finance_trial_balance via FinanceService.trialBalance",
    authoritativeSource: "Finance Phase 1/2 GL",
    includedStatuses: ["posted"],
    excludedStatuses: ["draft", "voided"],
    period: "asOf",
    branchScope: "branch",
    freshness: "query-time",
    permissions: [...FINANCE_PERMS],
    fallback: { mode: "unavailable", message: "Requires finance.manage and branch." },
  }),
  c({
    metricId: "finance.profit_loss",
    module: "finance",
    name: "Profit & loss",
    formula: "RPC finance_profit_loss via FinanceService.profitLoss",
    authoritativeSource: "FinanceService.profitLoss",
    includedStatuses: ["posted"],
    excludedStatuses: ["draft", "voided"],
    period: "range",
    branchScope: "branch",
    freshness: "query-time",
    permissions: [...FINANCE_PERMS],
    fallback: { mode: "unavailable", message: "Requires finance.manage and branch." },
  }),
  c({
    metricId: "finance.balance_sheet",
    module: "finance",
    name: "Balance sheet",
    formula: "RPC finance_balance_sheet via FinancePhase2Service.getBalanceSheet",
    authoritativeSource: "FinancePhase2Service.getBalanceSheet",
    includedStatuses: ["posted"],
    excludedStatuses: ["draft", "voided"],
    period: "asOf",
    branchScope: "branch",
    freshness: "query-time",
    permissions: [...FINANCE_PERMS],
    fallback: { mode: "unavailable", message: "Requires finance.manage and branch." },
  }),
  c({
    metricId: "finance.cash_flow",
    module: "finance",
    name: "Cash flow",
    formula: "RPC finance_cash_flow_indirect via FinancePhase2Service.getCashFlow",
    authoritativeSource: "FinancePhase2Service.getCashFlow",
    includedStatuses: ["posted"],
    excludedStatuses: ["draft", "voided"],
    period: "range",
    branchScope: "branch",
    freshness: "query-time",
    permissions: [...FINANCE_PERMS],
    fallback: { mode: "unavailable", message: "Requires finance.manage and branch." },
  }),
  c({
    metricId: "finance.receivables",
    module: "finance",
    name: "Receivables open",
    formula: "COUNT/SUM finance_ar_invoices where status in open set",
    authoritativeSource: "public.finance_ar_invoices",
    includedStatuses: ["issued", "partially_paid", "overdue"],
    excludedStatuses: ["draft", "voided", "paid"],
    period: "asOf",
    branchScope: "branch",
    freshness: "query-time",
    permissions: [...FINANCE_PERMS],
    fallback: { mode: "unavailable", message: "Requires branch + finance access." },
  }),
  c({
    metricId: "finance.payables",
    module: "finance",
    name: "Payables open",
    formula: "COUNT/SUM supplier_invoices awaiting payment / posted",
    authoritativeSource: "public.supplier_invoices",
    includedStatuses: ["approved", "posted", "partially_paid"],
    excludedStatuses: ["draft", "voided", "paid"],
    period: "asOf",
    branchScope: "branch",
    freshness: "query-time",
    permissions: [...FINANCE_PERMS],
    fallback: { mode: "unavailable", message: "Requires branch + finance access." },
  }),
  c({
    metricId: "finance.profit",
    module: "finance",
    name: "Net income",
    formula: "P&L netIncome from FinanceService (not recomputed)",
    authoritativeSource: "FinanceService.profitLoss.netIncome",
    includedStatuses: ["posted"],
    excludedStatuses: ["draft", "voided"],
    period: "range",
    branchScope: "branch",
    freshness: "query-time",
    permissions: [...FINANCE_PERMS],
    fallback: { mode: "unavailable", message: "Requires finance.manage and branch." },
  }),
  c({
    metricId: "finance.margin",
    module: "finance",
    name: "Profit margin",
    formula: "netIncome / revenue (from P&L envelope)",
    authoritativeSource: "FinanceService.profitLoss",
    includedStatuses: ["posted"],
    excludedStatuses: ["draft", "voided"],
    period: "range",
    branchScope: "branch",
    freshness: "query-time",
    permissions: [...FINANCE_PERMS],
    fallback: { mode: "null", message: "Null when revenue = 0." },
  }),

  // —— Product ——
  c({
    metricId: "product.top_items",
    module: "product",
    name: "Top products by quantity",
    formula: "GROUP BY order_items.menu_item_id SUM(quantity); label from order_items.product_name snapshot",
    authoritativeSource: "public.order_items.menu_item_id + product_name + public.orders",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "null", message: "No line items → empty list." },
  }),

  // —— Inventory ——
  c({
    metricId: "inventory.valuation",
    module: "inventory",
    name: "Inventory valuation",
    formula: "SUM(on_hand * cost_price) for active stock items in scope",
    authoritativeSource: "public.inventory_items / stock balances",
    includedStatuses: ["active"],
    excludedStatuses: ["archived", "inactive"],
    period: "asOf",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...INV_PERMS],
    fallback: { mode: "unavailable", message: "Unavailable when inventory scope empty." },
  }),
  c({
    metricId: "inventory.low_stock",
    module: "inventory",
    name: "Low stock count",
    formula: "COUNT items where on_hand < reorder_level",
    authoritativeSource: "inventory balances",
    includedStatuses: ["active"],
    excludedStatuses: [],
    period: "asOf",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...INV_PERMS],
    fallback: { mode: "zero", message: "0 when none below reorder." },
  }),
  c({
    metricId: "inventory.waste",
    module: "inventory",
    name: "Waste movements",
    formula: "SUM qty of stock_movements type=waste in range",
    authoritativeSource: "public.stock_movements",
    includedStatuses: ["waste"],
    excludedStatuses: [],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...INV_PERMS],
    fallback: { mode: "zero", message: "0 when no waste movements." },
  }),
  c({
    metricId: "inventory.adjustments",
    module: "inventory",
    name: "Adjustment movements",
    formula: "COUNT stock_movements type=adjustment in range",
    authoritativeSource: "public.stock_movements",
    includedStatuses: ["adjustment"],
    excludedStatuses: [],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...INV_PERMS],
    fallback: { mode: "zero", message: "0 when no adjustments." },
  }),
  c({
    metricId: "inventory.recipe_coverage",
    module: "inventory",
    name: "Recipe coverage",
    formula: "menu items with active recipe / sellable menu items",
    authoritativeSource: "inventory recipes + menu items",
    includedStatuses: ["active"],
    excludedStatuses: [],
    period: "asOf",
    branchScope: "organization",
    freshness: "query-time",
    permissions: [...INV_PERMS],
    fallback: { mode: "null", message: "Null when menu catalog empty." },
  }),

  // —— Procurement / Supplier ——
  c({
    metricId: "procurement.po_value",
    module: "procurement",
    name: "PO value",
    formula: "SUM(purchase_orders.total_amount) in range by status set",
    authoritativeSource: "public.purchase_orders",
    includedStatuses: ["submitted", "approved", "ordered", "partially_received", "received", "closed"],
    excludedStatuses: ["cancelled", "draft"],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...PUR_PERMS],
    fallback: { mode: "zero", message: "0 when no POs." },
  }),
  c({
    metricId: "procurement.grn_mismatch",
    module: "procurement",
    name: "GRN mismatch count",
    formula: "COUNT receiving exceptions / mismatched GRNs open",
    authoritativeSource: "purchasing receiving / exceptions",
    includedStatuses: ["open", "mismatch"],
    excludedStatuses: ["resolved"],
    period: "asOf",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...PUR_PERMS],
    fallback: { mode: "zero", message: "0 when no mismatches." },
  }),
  c({
    metricId: "supplier.performance",
    module: "supplier",
    name: "Supplier on-time rate",
    formula: "on_time receipts / total receipts (when timestamps exist)",
    authoritativeSource: "purchase receipts / supplier portal",
    includedStatuses: ["received"],
    excludedStatuses: [],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...PUR_PERMS],
    fallback: { mode: "unavailable", message: "UNAVAILABLE when SLA timestamps missing." },
  }),

  // —— Kitchen / Delivery ——
  c({
    metricId: "kitchen.waiting",
    module: "kitchen",
    name: "Kitchen tickets waiting",
    formula: "COUNT kitchen tickets in active prep statuses (ops dashboard)",
    authoritativeSource: "kitchen_tickets via ops summary",
    includedStatuses: ["queued", "preparing", "ready"],
    excludedStatuses: ["completed", "cancelled"],
    period: "asOf",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "0 when none waiting." },
  }),
  c({
    metricId: "delivery.active",
    module: "delivery",
    name: "Active deliveries",
    formula: "COUNT active delivery assignments",
    authoritativeSource: "delivery assignments",
    includedStatuses: ["assigned", "picked_up", "en_route"],
    excludedStatuses: ["delivered", "cancelled"],
    period: "asOf",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "0 when none active." },
  }),

  // —— Workforce / Payroll ——
  c({
    metricId: "workforce.attendance",
    module: "workforce",
    name: "Clocked-in employees",
    formula: "HrWorkforceService.getMetrics.employeesClockedIn",
    authoritativeSource: "HrWorkforceService.getMetrics",
    includedStatuses: ["open_session"],
    excludedStatuses: [],
    period: "asOf",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...HR_PERMS],
    fallback: { mode: "unavailable", message: "Workforce metrics unavailable." },
  }),
  c({
    metricId: "workforce.late_arrivals",
    module: "workforce",
    name: "Late arrivals today",
    formula: "HrWorkforceService.getMetrics.lateArrivalsToday",
    authoritativeSource: "HrWorkforceService.getMetrics",
    includedStatuses: ["late"],
    excludedStatuses: [],
    period: "asOfDate Asia/Karachi",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...HR_PERMS],
    fallback: { mode: "unavailable", message: "Workforce metrics unavailable." },
  }),
  c({
    metricId: "workforce.absence",
    module: "workforce",
    name: "Absences today",
    formula: "HrWorkforceService.getMetrics.absencesToday",
    authoritativeSource: "HrWorkforceService.getMetrics",
    includedStatuses: ["absent"],
    excludedStatuses: [],
    period: "asOfDate Asia/Karachi",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...HR_PERMS],
    fallback: { mode: "unavailable", message: "Workforce metrics unavailable." },
  }),
  c({
    metricId: "payroll.labour_cost",
    module: "payroll",
    name: "Labour cost",
    formula: "SUM approved/locked payroll run net when settlements exist; else UNAVAILABLE",
    authoritativeSource: "hr_payroll_runs + settlements",
    includedStatuses: ["approved", "payment_ready", "locked"],
    excludedStatuses: ["draft", "cancelled"],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...HR_PERMS],
    fallback: {
      mode: "unavailable",
      message: "Labour cost stays UNAVAILABLE without approved payroll totals in range.",
    },
  }),

  // —— Loyalty / Marketing / Customer ——
  c({
    metricId: "loyalty.members",
    module: "loyalty",
    name: "Loyalty members with balance",
    formula: "COUNT loyalty_accounts WHERE points_balance > 0 (via attention + accounts)",
    authoritativeSource: "LoyaltyService.getAttention / loyalty_accounts",
    includedStatuses: ["active"],
    excludedStatuses: [],
    period: "asOf",
    branchScope: "organization",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "unavailable", message: "Loyalty attention unavailable." },
  }),
  c({
    metricId: "loyalty.earned",
    module: "loyalty",
    name: "Points earned (liability snapshot)",
    formula: "SUM loyalty_transactions WHERE type=earn",
    authoritativeSource: "LoyaltyDepthService.getLiabilitySnapshot",
    includedStatuses: ["earn"],
    excludedStatuses: [],
    period: "lifetime-or-range",
    branchScope: "organization",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "unavailable", message: "Ledger unavailable." },
  }),
  c({
    metricId: "loyalty.redeemed",
    module: "loyalty",
    name: "Points redeemed",
    formula: "SUM loyalty_transactions WHERE type=burn",
    authoritativeSource: "LoyaltyDepthService.getLiabilitySnapshot",
    includedStatuses: ["burn"],
    excludedStatuses: [],
    period: "lifetime-or-range",
    branchScope: "organization",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "unavailable", message: "Ledger unavailable." },
  }),
  c({
    metricId: "loyalty.expired",
    module: "loyalty",
    name: "Points expired",
    formula: "SUM loyalty_transactions WHERE type=expire",
    authoritativeSource: "LoyaltyDepthService.getLiabilitySnapshot",
    includedStatuses: ["expire"],
    excludedStatuses: [],
    period: "lifetime-or-range",
    branchScope: "organization",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "0 when no expire txns." },
  }),
  c({
    metricId: "loyalty.redemption_rate",
    module: "loyalty",
    name: "Redemption rate",
    formula: "redeemed / earned * 100 (null when earned=0)",
    authoritativeSource: "LoyaltyDepthService.getLiabilitySnapshot",
    includedStatuses: [],
    excludedStatuses: [],
    period: "lifetime-or-range",
    branchScope: "organization",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "null", message: "Null when earned=0." },
  }),
  c({
    metricId: "marketing.redemptions",
    module: "marketing",
    name: "Coupon redemptions signal",
    formula: "MarketingService.getAttention + coupon_redemptions",
    authoritativeSource: "MarketingService.getAttention",
    includedStatuses: ["active", "redeemed"],
    excludedStatuses: [],
    period: "asOf",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "unavailable", message: "Marketing attention unavailable." },
  }),
  c({
    metricId: "marketing.campaigns_by_status",
    module: "marketing",
    name: "Campaigns by status",
    formula: "COUNT marketing_campaigns GROUP BY status",
    authoritativeSource: "public.marketing_campaigns",
    includedStatuses: [
      "draft",
      "awaiting_approval",
      "approved",
      "scheduled",
      "running",
      "paused",
      "completed",
      "cancelled",
    ],
    excludedStatuses: [],
    period: "asOf",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "0 when no campaigns." },
  }),
  c({
    metricId: "marketing.attributable_orders",
    module: "marketing",
    name: "Attributable orders",
    formula: "COUNT DISTINCT order_id FROM marketing_attribution_links",
    authoritativeSource: "MarketingDepthService.getAttributionSummary",
    includedStatuses: [],
    excludedStatuses: [],
    period: "asOf",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "0 when no attribution links." },
  }),
  c({
    metricId: "customer.new",
    module: "customer",
    name: "New customers",
    formula: "COUNT distinct contact_phone with first order in range",
    authoritativeSource: "public.orders.contact_phone",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "0 when no new phones." },
  }),
  c({
    metricId: "customer.returning",
    module: "customer",
    name: "Returning customers",
    formula: "COUNT distinct contact_phone with prior order before range and order in range",
    authoritativeSource: "public.orders.contact_phone",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "0 when none returning." },
  }),
  c({
    metricId: "customer.frequency",
    module: "customer",
    name: "Order frequency",
    formula: "order_count / distinct_customers in range",
    authoritativeSource: "public.orders",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "null", message: "Null when no customers." },
  }),

  // —— Branch comparison ——
  c({
    metricId: "branch.gross_sales",
    module: "branch_comparison",
    name: "Branch gross sales",
    formula: "GROUP BY branch_id SUM(total_amount) non-cancelled",
    authoritativeSource: "public.orders",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "range",
    branchScope: "organization",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "Empty branch list → empty series." },
  }),

  // —— Platform capabilities (contracts) ——
  c({
    metricId: "platform.scheduled_reports",
    module: "scheduled_reports",
    name: "Scheduled reports",
    formula: "COUNT analytics_scheduled_reports WHERE is_active; execution DEFERRED",
    authoritativeSource: "public.analytics_scheduled_reports",
    includedStatuses: ["deferred"],
    excludedStatuses: [],
    period: "asOf",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "deferred", message: "Execution deferred — no worker." },
  }),
  c({
    metricId: "platform.export_csv",
    module: "export_csv",
    name: "CSV export",
    formula: "Server-built CSV from analytics envelopes",
    authoritativeSource: "AnalyticsService.export",
    includedStatuses: [],
    excludedStatuses: [],
    period: "request",
    branchScope: "both",
    freshness: "request-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "unavailable", message: "Export denied without reports access." },
  }),
  c({
    metricId: "platform.export_excel",
    module: "export_excel",
    name: "Excel export",
    formula: "Server SpreadsheetML from analytics envelopes",
    authoritativeSource: "AnalyticsService.export",
    includedStatuses: [],
    excludedStatuses: [],
    period: "request",
    branchScope: "both",
    freshness: "request-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "unavailable", message: "Export denied without reports access." },
  }),
  c({
    metricId: "platform.export_pdf",
    module: "export_pdf",
    name: "PDF export",
    formula: "Server minimal PDF from analytics envelopes",
    authoritativeSource: "AnalyticsService.export",
    includedStatuses: [],
    excludedStatuses: [],
    period: "request",
    branchScope: "both",
    freshness: "request-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "unavailable", message: "Export denied without reports access." },
  }),
  c({
    metricId: "platform.drill_down",
    module: "drill_down",
    name: "Drill down",
    formula: "Row-level detail for metricId via AnalyticsService.drillDown",
    authoritativeSource: "domain tables per metric contract",
    includedStatuses: [],
    excludedStatuses: [],
    period: "request",
    branchScope: "both",
    freshness: "request-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "unavailable", message: "Unknown metricId." },
  }),
  c({
    metricId: "platform.formula_registry",
    module: "formula_registry",
    name: "Formula registry",
    formula: "Static FORMULA_REGISTRY export",
    authoritativeSource: "services/analytics/registry.ts",
    includedStatuses: [],
    excludedStatuses: [],
    period: "n/a",
    branchScope: "organization",
    freshness: REGISTRY_VERSION,
    permissions: [...BASE_PERMS],
    fallback: { mode: "unavailable", message: "Registry always LIVE in process." },
  }),
  c({
    metricId: "platform.metric_contracts",
    module: "metric_contracts",
    name: "Metric contracts",
    formula: "Same as formula registry; contract fields required",
    authoritativeSource: "services/analytics/registry.ts",
    includedStatuses: [],
    excludedStatuses: [],
    period: "n/a",
    branchScope: "organization",
    freshness: REGISTRY_VERSION,
    permissions: [...BASE_PERMS],
    fallback: { mode: "unavailable", message: "Contracts always LIVE in process." },
  }),
  c({
    metricId: "platform.data_quality",
    module: "data_quality",
    name: "Data quality checks",
    formula: "Engine runs reconciliation checks; persists snapshots",
    authoritativeSource: "AnalyticsService.runDataQuality",
    includedStatuses: ["pass", "warn", "fail"],
    excludedStatuses: [],
    period: "asOf",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "unavailable", message: "Quality unavailable without DB." },
  }),
  c({
    metricId: "platform.exceptions",
    module: "exception_center",
    name: "Open analytics exceptions",
    formula: "COUNT analytics_exceptions WHERE status=open",
    authoritativeSource: "public.analytics_exceptions",
    includedStatuses: ["open"],
    excludedStatuses: ["resolved"],
    period: "asOf",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "0 when none open." },
  }),
  c({
    metricId: "platform.owner_workspace",
    module: "owner_bi_workspace",
    name: "Owner BI workspace",
    formula: "Compose module snapshots via AnalyticsService.getOwnerWorkspace",
    authoritativeSource: "AnalyticsService",
    includedStatuses: [],
    excludedStatuses: [],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "unavailable", message: "Requires reports access." },
  }),
  c({
    metricId: "executive.overview_orders",
    module: "executive",
    name: "Executive order count",
    formula: "sales order_count for period",
    authoritativeSource: "public.orders via sales module",
    includedStatuses: ["pending", "confirmed", "preparing", "ready", "dispatched", "completed"],
    excludedStatuses: ["cancelled"],
    period: "range",
    branchScope: "both",
    freshness: "query-time",
    permissions: [...BASE_PERMS],
    fallback: { mode: "zero", message: "0 when no orders." },
  }),
];

export function getMetricContract(metricId: string): MetricContract | undefined {
  return FORMULA_REGISTRY.find((m) => m.metricId === metricId);
}

export function listMetricsForModule(moduleId: AnalyticsModuleId): MetricContract[] {
  return FORMULA_REGISTRY.filter((m) => m.module === moduleId);
}

export function listRegistryModules(): Array<{
  moduleId: AnalyticsModuleId;
  metricCount: number;
  title: string;
}> {
  const titles: Record<AnalyticsModuleId, string> = {
    executive: "Executive Analytics",
    sales: "Sales Analytics",
    finance: "Finance Analytics",
    product: "Product Analytics",
    inventory: "Inventory Analytics",
    procurement: "Procurement Analytics",
    supplier: "Supplier Analytics",
    kitchen: "Kitchen Analytics",
    delivery: "Delivery Analytics",
    workforce: "Workforce Analytics",
    payroll: "Payroll Analytics",
    loyalty: "Loyalty Analytics",
    marketing: "Marketing Analytics",
    customer: "Customer Analytics",
    branch_comparison: "Branch Comparison",
    scheduled_reports: "Scheduled Reports",
    export_csv: "CSV Export",
    export_excel: "Excel Export",
    export_pdf: "PDF Export",
    drill_down: "Drill Down",
    formula_registry: "KPI Formula Registry",
    metric_contracts: "Metric Contracts",
    data_quality: "Data Quality Center",
    exception_center: "Analytics Exception Center",
    owner_bi_workspace: "Owner BI Workspace",
  };
  return (Object.keys(titles) as AnalyticsModuleId[]).map((moduleId) => ({
    moduleId,
    title: titles[moduleId],
    metricCount: listMetricsForModule(moduleId).length,
  }));
}
